"""Clinical concept normalization with pluggable terminology backends."""

from __future__ import annotations

from .backend import (
    SYNTHETIC_CODE_SYSTEMS,
    SYNTHETIC_CONCEPTS,
    BackendIdentity,
    CodeSystemMetadata,
    SyntheticTerminologyBackend,
    TerminologyBackend,
    TerminologyConcept,
    normalize_surface,
    validate_backend_identity,
)
from .cache import (
    ConceptNormalizationCache,
    NormalizationCacheStats,
    make_normalization_cache_key,
)
from .india_terminology import (
    AYUSH,
    DEFAULT_AYUSH_SYSTEM_URI,
    DEFAULT_INDIAN_DRUG_SYSTEM_URI,
    INDIA_TERMINOLOGY_KINDS,
    INDIAN_DRUG,
    GroundedIndiaTerm,
    IndiaTerminologyDictionary,
    IndiaTerminologyError,
    IndiaTerminologyFormatError,
    IndiaTerminologyKind,
    IndiaTerminologyLoader,
    IndiaTerminologyLoadResult,
    TerminologySkipNotice,
    UserSuppliedIndiaTerminology,
    normalize_india_terminology_surface,
)
from .ranker import (
    SYNTHETIC_GOLD_SET,
    CandidateProvenance,
    ConceptNormalizer,
    NormalizationEvaluationResult,
    NormalizationGoldCase,
    RankedConcept,
    evaluate_normalization_gold,
    generate_query_variants,
)

__all__ = [
    "BackendIdentity",
    "AYUSH",
    "CandidateProvenance",
    "CodeSystemMetadata",
    "ConceptNormalizationCache",
    "ConceptNormalizer",
    "DEFAULT_AYUSH_SYSTEM_URI",
    "DEFAULT_INDIAN_DRUG_SYSTEM_URI",
    "GroundedIndiaTerm",
    "INDIA_TERMINOLOGY_KINDS",
    "INDIAN_DRUG",
    "IndiaTerminologyDictionary",
    "IndiaTerminologyError",
    "IndiaTerminologyFormatError",
    "IndiaTerminologyKind",
    "IndiaTerminologyLoadResult",
    "IndiaTerminologyLoader",
    "NormalizationCacheStats",
    "NormalizationEvaluationResult",
    "NormalizationGoldCase",
    "RankedConcept",
    "SYNTHETIC_CODE_SYSTEMS",
    "SYNTHETIC_CONCEPTS",
    "SYNTHETIC_GOLD_SET",
    "SyntheticTerminologyBackend",
    "TerminologySkipNotice",
    "TerminologyBackend",
    "TerminologyConcept",
    "UserSuppliedIndiaTerminology",
    "evaluate_normalization_gold",
    "generate_query_variants",
    "make_normalization_cache_key",
    "normalize_surface",
    "normalize_india_terminology_surface",
    "validate_backend_identity",
]
