"""Custom Faker providers for clinical / national IDs that Faker doesn't
cover natively or covers with the wrong format.

These providers integrate with Faker's standard ``add_provider`` mechanism
and produce values that pass the existing checksum validators in
:mod:`openmed.core.pii_i18n`.
"""

from .clinical_ids import (
    AadhaarProvider,
    BulgarianEgnProvider,
    DanishCPRProvider,
    EstonianIsikukoodProvider,
    FinancialIdentifierProvider,
    GermanSteuerIdProvider,
    HungarianTAJProvider,
    IndonesianNIKProvider,
    IsraeliTeudatZehutProvider,
    KoreanRRNProvider,
    LatvianPersonasKodsProvider,
    MedicalRecordNumberProvider,
    NPIProvider,
    PhilippinesIdProvider,
    PolishPeselProvider,
    PortugueseNIFProvider,
    RomanianCNPProvider,
    SerbianJmbgProvider,
    SpanishDNIProvider,
    VietnameseIdProvider,
    generate_bic,
    generate_bulgarian_egn,
    generate_danish_cpr,
    generate_estonian_isikukood,
    generate_hungarian_taj,
    generate_iban,
    generate_indonesian_nik,
    generate_jmbg,
    generate_korean_rrn,
    generate_latvian_personas_kods,
    generate_pesel,
    generate_philhealth_pin,
    generate_philsys_psn,
    generate_portuguese_nif,
    generate_romanian_cnp,
    generate_teudat_zehut,
    generate_vietnamese_cccd,
    generate_vietnamese_cmnd,
    register_clinical_providers,
)
from .registry_ids import (
    ID_PROVIDER_REGISTRY,
    NationalIdSpec,
    get_national_id,
    register_national_id,
)
from .script_names import (
    DEVANAGARI_LANGUAGE_PACK,
    HAN_LANGUAGE_PACK,
    SCRIPT_NAME_PACKS,
    TELUGU_LANGUAGE_PACK,
    generate_devanagari_name,
    generate_han_name,
    generate_telugu_name,
)

__all__ = [
    "AadhaarProvider",
    "BulgarianEgnProvider",
    "DanishCPRProvider",
    "DEVANAGARI_LANGUAGE_PACK",
    "EstonianIsikukoodProvider",
    "FinancialIdentifierProvider",
    "GermanSteuerIdProvider",
    "HungarianTAJProvider",
    "HAN_LANGUAGE_PACK",
    "ID_PROVIDER_REGISTRY",
    "IndonesianNIKProvider",
    "IsraeliTeudatZehutProvider",
    "KoreanRRNProvider",
    "LatvianPersonasKodsProvider",
    "MedicalRecordNumberProvider",
    "NPIProvider",
    "NationalIdSpec",
    "PhilippinesIdProvider",
    "PolishPeselProvider",
    "PortugueseNIFProvider",
    "RomanianCNPProvider",
    "SerbianJmbgProvider",
    "SCRIPT_NAME_PACKS",
    "SpanishDNIProvider",
    "TELUGU_LANGUAGE_PACK",
    "VietnameseIdProvider",
    "generate_bic",
    "generate_bulgarian_egn",
    "generate_danish_cpr",
    "generate_devanagari_name",
    "generate_hungarian_taj",
    "generate_han_name",
    "generate_estonian_isikukood",
    "generate_iban",
    "generate_indonesian_nik",
    "generate_jmbg",
    "generate_teudat_zehut",
    "generate_telugu_name",
    "generate_vietnamese_cccd",
    "generate_vietnamese_cmnd",
    "generate_korean_rrn",
    "generate_latvian_personas_kods",
    "generate_philhealth_pin",
    "generate_philsys_psn",
    "generate_pesel",
    "generate_portuguese_nif",
    "generate_romanian_cnp",
    "get_national_id",
    "register_clinical_providers",
    "register_national_id",
]
